# -*- coding: utf-8 -*-

def main():
    startApplication("EmotivXavierControlpanel")
    clickButton(waitForObject(":InsightEpocControlPanelClass.accountBtn_QPushButton"))
    test.compare(str(waitForObjectExists(":InsightEpocControlPanelClass.accountBtn_QPushButton").text), "Add User")
    mouseClick(waitForObject(":InsightEpocControlPanelClass.background_QWidget"), 763, 6, 0, Qt.LeftButton)
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnLoginMultiAcc_QPushButton"))
    type(waitForObject(":InsightEpocControlPanelClass.txtUserNameNext_QLineEdit"), "thamvu")
    type(waitForObject(":InsightEpocControlPanelClass.txtUserNameNext_QLineEdit"), "<Tab>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "Humg19")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "<Backspace>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "Humg1991")
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnLoginUserNext_QPushButton"))
    # wait to login with user thamvu
    snooze(10)
    clickButton(waitForObject(":InsightEpocControlPanelClass.accountBtn_QPushButton"))
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnLoginMultiAcc_QPushButton"))
    type(waitForObject(":InsightEpocControlPanelClass.txtUserNameNext_QLineEdit"), "thamvu.emotiv1")
    type(waitForObject(":InsightEpocControlPanelClass.txtUserNameNext_QLineEdit"), "<Tab>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "Humg1992")
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnLoginUserNext_QPushButton"))
    # wait to login with user thamvu.emotiv1
    snooze(10)
    clickButton(waitForObject(":InsightEpocControlPanelClass.accountBtn_QPushButton"))
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnShowMultiAcc_QPushButton"))
    waitForObjectItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu")
    clickItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu", 29, 7, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu")
    clickItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu", 44, 6, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu\\.emotiv1")
    clickItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu\\.emotiv1", 83, 11, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu\\.emotiv1")
    doubleClickItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu\\.emotiv1", 83, 11, 0, Qt.LeftButton)
    clickButton(waitForObject(":InsightEpocControlPanelClass.accountBtn_QPushButton"))
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnShowMultiAcc_QPushButton"))
    waitForObjectItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu")
    clickItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu", 25, 13, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu")
    doubleClickItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu", 25, 13, 0, Qt.LeftButton)
    # wait to change from user thamvu.emotiv1 to user thamvu
    snooze(10)
    clickButton(waitForObject(":InsightEpocControlPanelClass.accountBtn_QPushButton"))
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnShowMultiAcc_QPushButton"))
    waitForObjectItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu\\.emotiv1")
    clickItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu\\.emotiv1", 32, 11, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu\\.emotiv1")
    doubleClickItem(":InsightEpocControlPanelClass.multiAccountListWidget_QListWidget", "thamvu\\.emotiv1", 32, 11, 0, Qt.LeftButton)
    clickButton(waitForObject(":InsightEpocControlPanelClass.accountBtn_QPushButton"))
    # wait to change from user thamvu to user thamvu.emotiv1
    snooze(10)
