# -*- coding: utf-8 -*-

def main():
    startApplication("EmotivXavierControlpanel")
    clickButton(waitForObject(":InsightEpocControlPanelClass.accountBtn_QPushButton"))
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnLoginMultiAcc_QPushButton"))
    type(waitForObject(":InsightEpocControlPanelClass.txtUserNameNext_QLineEdit"), "thamvu")
    type(waitForObject(":InsightEpocControlPanelClass.txtUserNameNext_QLineEdit"), "<Tab>")
    type(waitForObject(":InsightEpocControlPanelClass.txtPassWNext_QLineEdit"), "Humg1991")
    clickButton(waitForObject(":InsightEpocControlPanelClass.btnLoginUserNext_QPushButton"))
    # wait to login
    snooze(10)
    test.compare(str(waitForObjectExists(":InsightEpocControlPanelClass.accountBtn_QPushButton").text), "thamvu")
    clickButton(waitForObject(":InsightEpocControlPanelClass.menuPushButton_QPushButton"))
    clickButton(waitForObject(":menuGroupBox.reportsMenuButton_QPushButton"))
    test.compare(str(waitForObjectExists(":InsightEpocControlPanelClass.label_6_QLabel").text), "> REPORTS")
    test.compare(waitForObjectExists(": Name _HeaderViewItem").text, " Name ")
    test.compare(waitForObjectExists(": Rating _HeaderViewItem").text, " Rating ")
    test.compare(waitForObjectExists(": Date _HeaderViewItem").text, " Date ")
    waitForObjectItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "0/0")
    clickItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "0/0", 48, 11, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "0/0")
    doubleClickItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "0/0", 48, 11, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "0/0")
    clickItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "0/0", 49, 8, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "2/0")
    doubleClickItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "2/0", 61, 8, 0, Qt.LeftButton)
    waitForObjectItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "0/0")
    doubleClickItem(":InsightEpocControlPanelClass.reportTableWdg_QTableWidget", "0/0", 65, 19, 0, Qt.LeftButton)
    test.compare(str(waitForObjectExists(":InsightEpocControlPanelClass.durationLabel_QLabel").text), "Duration :")
    test.compare(str(waitForObjectExists(":InsightEpocControlPanelClass.dateLabel_QLabel").text), "Date :")
    test.compare(str(waitForObjectExists(":InsightEpocControlPanelClass.timeLabel_QLabel").text), "Time :")
    test.compare(str(waitForObjectExists(":InsightEpocControlPanelClass.label_3_QLabel").text), "ADD NOTES:")
